import type { RIASECType } from '@/types'

export interface Profession {
  id: string
  name: string
  emoji: string
  shortDesc: string
  riasecPrimary: RIASECType
  riasecSecondary?: RIASECType
  salaryRange: string
  dayInLife: string
  subjects: string[]
  gameAvailable: boolean
  color: string
}

export const PROFESSIONS: Profession[] = [
  // ── Realistic ────────────────────────────────────────────────
  {
    id: 'engineer',
    name: 'Инженер-конструктор',
    emoji: '⚙️',
    shortDesc: 'Проектирует машины, здания и системы — превращает идеи в рабочие устройства',
    riasecPrimary: 'realistic',
    riasecSecondary: 'investigative',
    salaryRange: '80 000 – 250 000 ₽',
    dayInLife: 'Утро: чертежи и расчёты в CAD. День: совещание с командой, исправление моделей. Вечер: тестирование прототипа.',
    subjects: ['Физика', 'Математика', 'Черчение', 'Информатика'],
    gameAvailable: false,
    color: 'bg-slate-50 border-slate-200',
  },
  {
    id: 'pilot',
    name: 'Пилот',
    emoji: '✈️',
    shortDesc: 'Управляет воздушными судами — связывает города и страны',
    riasecPrimary: 'realistic',
    salaryRange: '200 000 – 500 000 ₽',
    dayInLife: 'Предполётный брифинг, проверка систем, взлёт — и 8 часов над облаками, где ты ответственен за сотни людей.',
    subjects: ['Физика', 'Математика', 'Английский язык', 'География'],
    gameAvailable: false,
    color: 'bg-sky-50 border-sky-200',
  },
  {
    id: 'architect',
    name: 'Архитектор',
    emoji: '🏛️',
    shortDesc: 'Создаёт здания, которые стоят десятилетия и меняют городскую среду',
    riasecPrimary: 'realistic',
    riasecSecondary: 'artistic',
    salaryRange: '80 000 – 300 000 ₽',
    dayInLife: 'Работа с макетами и 3D-моделями, переговоры с заказчиком, выезд на стройку для контроля.',
    subjects: ['Черчение', 'Математика', 'Изобразительное искусство', 'Физика'],
    gameAvailable: false,
    color: 'bg-stone-50 border-stone-200',
  },
  {
    id: 'surgeon',
    name: 'Хирург',
    emoji: '🔬',
    shortDesc: 'Спасает жизни с помощью точных операций — работа руками на грани искусства',
    riasecPrimary: 'realistic',
    riasecSecondary: 'social',
    salaryRange: '120 000 – 400 000 ₽',
    dayInLife: 'Утренний обход пациентов, 4-6 часов в операционной, разбор сложных случаев с командой.',
    subjects: ['Биология', 'Химия', 'Физика', 'Математика'],
    gameAvailable: false,
    color: 'bg-green-50 border-green-200',
  },

  // ── Investigative ────────────────────────────────────────────
  {
    id: 'programmer',
    name: 'Программист',
    emoji: '💻',
    shortDesc: 'Пишет код, который запускает приложения, игры и сервисы для миллионов людей',
    riasecPrimary: 'investigative',
    riasecSecondary: 'conventional',
    salaryRange: '100 000 – 500 000 ₽',
    dayInLife: 'Анализ задачи, написание и отладка кода, code review с командой, деплой новых функций.',
    subjects: ['Информатика', 'Математика', 'Английский язык', 'Физика'],
    gameAvailable: true,
    color: 'bg-indigo-50 border-indigo-200',
  },
  {
    id: 'data-scientist',
    name: 'Аналитик данных',
    emoji: '📊',
    shortDesc: 'Находит скрытые закономерности в данных и помогает компаниям принимать умные решения',
    riasecPrimary: 'investigative',
    riasecSecondary: 'conventional',
    salaryRange: '120 000 – 400 000 ₽',
    dayInLife: 'Выгрузка данных, построение графиков и моделей на Python, презентация инсайтов руководству.',
    subjects: ['Математика', 'Статистика', 'Информатика', 'Экономика'],
    gameAvailable: false,
    color: 'bg-blue-50 border-blue-200',
  },
  {
    id: 'doctor',
    name: 'Врач',
    emoji: '🏥',
    shortDesc: 'Диагностирует болезни и помогает людям восстановить здоровье',
    riasecPrimary: 'investigative',
    riasecSecondary: 'social',
    salaryRange: '80 000 – 300 000 ₽',
    dayInLife: 'Приём пациентов, изучение анализов, назначение лечения, консультации с коллегами.',
    subjects: ['Биология', 'Химия', 'Физика', 'Математика'],
    gameAvailable: true,
    color: 'bg-rose-50 border-rose-200',
  },
  {
    id: 'scientist',
    name: 'Учёный-исследователь',
    emoji: '🔭',
    shortDesc: 'Открывает новые законы природы и двигает человечество вперёд',
    riasecPrimary: 'investigative',
    salaryRange: '60 000 – 200 000 ₽',
    dayInLife: 'Проведение экспериментов в лаборатории, анализ результатов, написание статей, конференции.',
    subjects: ['Физика', 'Химия', 'Биология', 'Математика'],
    gameAvailable: true,
    color: 'bg-purple-50 border-purple-200',
  },
  {
    id: 'cybersecurity',
    name: 'Специалист по кибербезопасности',
    emoji: '🛡️',
    shortDesc: 'Защищает системы от хакеров и предотвращает утечки данных',
    riasecPrimary: 'investigative',
    riasecSecondary: 'realistic',
    salaryRange: '150 000 – 600 000 ₽',
    dayInLife: 'Тестирование систем на уязвимости, анализ атак, настройка защиты, обучение сотрудников.',
    subjects: ['Информатика', 'Математика', 'Физика', 'Английский язык'],
    gameAvailable: false,
    color: 'bg-gray-50 border-gray-200',
  },

  // ── Artistic ─────────────────────────────────────────────────
  {
    id: 'designer',
    name: 'UX/UI Дизайнер',
    emoji: '🎨',
    shortDesc: 'Делает приложения и сайты удобными и красивыми — думает за пользователя',
    riasecPrimary: 'artistic',
    riasecSecondary: 'investigative',
    salaryRange: '80 000 – 350 000 ₽',
    dayInLife: 'Исследование пользователей, создание прототипов в Figma, тестирование с реальными людьми.',
    subjects: ['Изобразительное искусство', 'Информатика', 'Психология', 'Математика'],
    gameAvailable: true,
    color: 'bg-amber-50 border-amber-200',
  },
  {
    id: 'filmmaker',
    name: 'Режиссёр',
    emoji: '🎬',
    shortDesc: 'Создаёт фильмы и сериалы — управляет командой и воплощает истории на экране',
    riasecPrimary: 'artistic',
    riasecSecondary: 'enterprising',
    salaryRange: '80 000 – 1 000 000 ₽',
    dayInLife: 'Утро: разбор сценария. День: съёмки на площадке. Вечер: просмотр материала, монтажные правки.',
    subjects: ['Литература', 'История', 'МХК', 'Иностранный язык'],
    gameAvailable: false,
    color: 'bg-red-50 border-red-200',
  },
  {
    id: 'journalist',
    name: 'Журналист',
    emoji: '📰',
    shortDesc: 'Находит правду и рассказывает истории, которые меняют мнение общества',
    riasecPrimary: 'artistic',
    riasecSecondary: 'social',
    salaryRange: '50 000 – 200 000 ₽',
    dayInLife: 'Сбор информации, интервью с источниками, написание материала в сжатые сроки, редактура.',
    subjects: ['Русский язык', 'Литература', 'История', 'Обществознание'],
    gameAvailable: true,
    color: 'bg-yellow-50 border-yellow-200',
  },
  {
    id: 'game-developer',
    name: 'Гейм-дизайнер',
    emoji: '🎮',
    shortDesc: 'Придумывает механики игр, уровни и персонажей — создаёт миры из ничего',
    riasecPrimary: 'artistic',
    riasecSecondary: 'investigative',
    salaryRange: '80 000 – 350 000 ₽',
    dayInLife: 'Написание дизайн-документов, прототипирование механик, плейтестирование, баланс и итерации.',
    subjects: ['Информатика', 'Математика', 'Изобразительное искусство', 'Психология'],
    gameAvailable: false,
    color: 'bg-violet-50 border-violet-200',
  },
  {
    id: 'photographer',
    name: 'Фотограф / Видеограф',
    emoji: '📸',
    shortDesc: 'Ловит момент и создаёт визуальные истории через объектив',
    riasecPrimary: 'artistic',
    salaryRange: '60 000 – 300 000 ₽',
    dayInLife: 'Съёмки в студии или на выезде, ретушь в Lightroom, общение с клиентами, поиск новых идей.',
    subjects: ['Изобразительное искусство', 'МХК', 'Физика', 'Иностранный язык'],
    gameAvailable: false,
    color: 'bg-orange-50 border-orange-200',
  },

  // ── Social ───────────────────────────────────────────────────
  {
    id: 'psychologist',
    name: 'Психолог',
    emoji: '🧠',
    shortDesc: 'Помогает людям справляться с трудностями, понимать себя и строить счастливую жизнь',
    riasecPrimary: 'social',
    riasecSecondary: 'investigative',
    salaryRange: '60 000 – 250 000 ₽',
    dayInLife: 'Индивидуальные сессии с клиентами, групповые тренинги, супервизия, чтение профессиональной литературы.',
    subjects: ['Биология', 'Обществознание', 'Русский язык', 'История'],
    gameAvailable: true,
    color: 'bg-teal-50 border-teal-200',
  },
  {
    id: 'teacher',
    name: 'Учитель',
    emoji: '📚',
    shortDesc: 'Передаёт знания и зажигает интерес — формирует будущих учёных, врачей и предпринимателей',
    riasecPrimary: 'social',
    salaryRange: '40 000 – 150 000 ₽',
    dayInLife: 'Уроки, проверка работ, подготовка к занятиям, помощь ученикам после уроков, олимпиады.',
    subjects: ['Педагогика', 'Психология', 'Профильный предмет'],
    gameAvailable: true,
    color: 'bg-lime-50 border-lime-200',
  },
  {
    id: 'social-worker',
    name: 'Социальный работник',
    emoji: '🤝',
    shortDesc: 'Помогает людям в трудной жизненной ситуации найти выход и поддержку',
    riasecPrimary: 'social',
    salaryRange: '35 000 – 100 000 ₽',
    dayInLife: 'Посещение подопечных, помощь с документами, координация с госорганами, консультации семей.',
    subjects: ['Обществознание', 'Право', 'Психология', 'Биология'],
    gameAvailable: false,
    color: 'bg-pink-50 border-pink-200',
  },
  {
    id: 'hr',
    name: 'HR-специалист',
    emoji: '👥',
    shortDesc: 'Находит лучших людей в команду и создаёт среду, где хочется работать',
    riasecPrimary: 'social',
    riasecSecondary: 'enterprising',
    salaryRange: '60 000 – 250 000 ₽',
    dayInLife: 'Собеседования с кандидатами, адаптация новых сотрудников, решение конфликтов, тренинги.',
    subjects: ['Обществознание', 'Психология', 'Русский язык', 'Иностранный язык'],
    gameAvailable: false,
    color: 'bg-fuchsia-50 border-fuchsia-200',
  },

  // ── Enterprising ─────────────────────────────────────────────
  {
    id: 'entrepreneur',
    name: 'Предприниматель',
    emoji: '🚀',
    shortDesc: 'Создаёт бизнес из нуля — берёт на себя риск ради большой идеи',
    riasecPrimary: 'enterprising',
    salaryRange: '0 – ∞ ₽',
    dayInLife: 'Встречи с командой, переговоры с партнёрами, анализ метрик, решение кризисов в режиме реального времени.',
    subjects: ['Математика', 'Экономика', 'Обществознание', 'Иностранный язык'],
    gameAvailable: true,
    color: 'bg-orange-50 border-orange-200',
  },
  {
    id: 'marketer',
    name: 'Маркетолог',
    emoji: '📣',
    shortDesc: 'Рассказывает миру о продукте так, чтобы люди хотели его купить',
    riasecPrimary: 'enterprising',
    riasecSecondary: 'artistic',
    salaryRange: '70 000 – 300 000 ₽',
    dayInLife: 'Анализ аудитории, запуск рекламных кампаний, создание контента, A/B тесты, отчёты.',
    subjects: ['Математика', 'Русский язык', 'Информатика', 'Психология'],
    gameAvailable: false,
    color: 'bg-rose-50 border-rose-200',
  },
  {
    id: 'lawyer',
    name: 'Юрист',
    emoji: '⚖️',
    shortDesc: 'Защищает права людей и компаний, разбирается в сложных законах',
    riasecPrimary: 'enterprising',
    riasecSecondary: 'conventional',
    salaryRange: '80 000 – 500 000 ₽',
    dayInLife: 'Изучение документов, переговоры, подготовка к суду, консультации клиентов.',
    subjects: ['Обществознание', 'История', 'Русский язык', 'Иностранный язык'],
    gameAvailable: false,
    color: 'bg-neutral-50 border-neutral-200',
  },
  {
    id: 'project-manager',
    name: 'Менеджер проектов',
    emoji: '📋',
    shortDesc: 'Доводит сложные проекты до результата — организует людей, ресурсы и сроки',
    riasecPrimary: 'enterprising',
    riasecSecondary: 'conventional',
    salaryRange: '100 000 – 400 000 ₽',
    dayInLife: 'Стендапы с командой, управление рисками, переговоры со стейкхолдерами, планирование спринтов.',
    subjects: ['Математика', 'Информатика', 'Иностранный язык', 'Экономика'],
    gameAvailable: false,
    color: 'bg-cyan-50 border-cyan-200',
  },

  // ── Conventional ─────────────────────────────────────────────
  {
    id: 'accountant',
    name: 'Финансовый аналитик',
    emoji: '💰',
    shortDesc: 'Следит за деньгами компании и находит способы зарабатывать больше',
    riasecPrimary: 'conventional',
    riasecSecondary: 'investigative',
    salaryRange: '80 000 – 350 000 ₽',
    dayInLife: 'Финансовые модели в Excel, подготовка отчётов, встречи с CFO, прогнозирование.',
    subjects: ['Математика', 'Экономика', 'Информатика'],
    gameAvailable: false,
    color: 'bg-emerald-50 border-emerald-200',
  },
  {
    id: 'logistician',
    name: 'Логист',
    emoji: '🚢',
    shortDesc: 'Организует движение товаров так, чтобы всё доходило вовремя и без потерь',
    riasecPrimary: 'conventional',
    riasecSecondary: 'realistic',
    salaryRange: '60 000 – 200 000 ₽',
    dayInLife: 'Планирование маршрутов, контроль складов, работа с поставщиками, оптимизация цепочек поставок.',
    subjects: ['Математика', 'География', 'Экономика', 'Иностранный язык'],
    gameAvailable: false,
    color: 'bg-blue-50 border-blue-200',
  },
  {
    id: 'chef',
    name: 'Шеф-повар',
    emoji: '👨‍🍳',
    shortDesc: 'Создаёт блюда, которые удивляют и запоминаются — кухня как сцена',
    riasecPrimary: 'realistic',
    riasecSecondary: 'artistic',
    salaryRange: '60 000 – 400 000 ₽',
    dayInLife: 'Утро: закупка продуктов. День: подготовка и приготовление. Вечер: сервис, управление командой кухни.',
    subjects: ['Химия', 'Биология', 'Изобразительное искусство'],
    gameAvailable: true,
    color: 'bg-amber-50 border-amber-200',
  },
]

export function getProfessionById(id: string): Profession | undefined {
  return PROFESSIONS.find(p => p.id === id)
}

export function getProfessionsByRiasec(type: RIASECType, limit = 4): Profession[] {
  return PROFESSIONS.filter(p => p.riasecPrimary === type || p.riasecSecondary === type)
    .slice(0, limit)
}

export function getProfessionsForGame(): Profession[] {
  return PROFESSIONS.filter(p => p.gameAvailable)
}
